= mill-osgi - Build OSGi Bundles with mill
:mill-osgi-version: 0.0.4
:toc:
:toc-placement: preamble


Plug-in to build OSGi bundles with the https://github.com/lihaoyi/mill[mill build tool]

== Quickstart

.File: `build.sc`
[source,scala,subs="verbatim,attributes"]
----
import $ivy.`de.tototec::de.tobiasroeser.mill.osgi:{mill-osgi-version}`
import de.tobiasroeser.mill.osgi._

object project extends ScalaModule with OsgiBundleModule {

  def bundleSymbolicName = "com.example.project"

  def osgiHeaders = T{ osgiHeaders().copy(
    `Export-Package`   = Seq("com.example.api"),
    `Bundle-Activator` = Some("com.example.internal.Activator")
  )}

}
----

== Defaults

By default mill-osgi tries to provide some sensible default values based on the current build setup.

=== `Export-Package` and `Private-Package`

By default, all output packages of the `compile` task will be added to the `Private-Package` header.
No packages will be exported via `Export-Package`.

=== `Bundle-SymbolicName`

If the module does not extends `PublishModule`, the bundle symbolic name will be initializes with `JavaModule.artifactName`.

If the module extends `PublishModule`, the `Bundle-SymbolicName` is computed using from `PublishModule.pomSettings.organization` and `JavaModule.artifactName`.
If the organization or the last segment of the organization is a prefix of the artifactName, than that redundant part is omited.


== License

Apache License, version 2

== Changelog

=== {master}

* Reworked integration test setup
* Version bump to mill-0.3.5 and use of os-lib

=== mill-osgi 0.0.4 - 2018-11-20

* Added explicit scala-library dependency to released pom.xml

=== mill-osgi 0.0.3 - 2018-11-02

* Changed packaging / pom dependency information so that loading
  into mill excludes mill dependencies

=== mill-osgi 0.0.2 - 2018-10-18

* Improved default bundle symbolic name algorithm
* Added support for -includeresource
* Improved source docs
* Don't add non-existing resources to avoid bnd warnings/errors
* Add more default headers when project is a `PublishModule` 

=== mill-osgi 0.0.1 - 2018-10-10

* Initial early release to gain user feedback

